apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    tier: web
    project: expense
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: frontend 
      tier: web
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        tier: web
        project: expense
    spec:
      containers:
      - name: frontend
        image: mahadevan045/frontend:{{ .Values.deployment.imageVersion }}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits: #limits is greater than or equal to requests
            cpu: 100m
            memory: 128Mi